### ISSUE TITLE
USB device port problems

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#10]
BQ25895 power negotiation is faulty and causes issues.

If we disable the power negotiation the vbus line of the usb port will always be 5v and thus it will be usable to power the usb hub directly.

- [x] Disconnect D+/D- from the BQ25895
- [x] Disconnect reset of USB hub from DSEL
- [x] Connect V5 pin of USB hub to USB_VBUS

**Comment by ranzbak** [comment]
Put solder jumper in place, so the USB data lines are disconnected by default but can used when debugging.

**Comment by renzenicolai** [comment]
In the end I just removed the USB port pins of the CH32. The usb serial converter idea of @ranzbak is much better so let's go with that.
