### ISSUE TITLE
Space behind the screw holes for the extension board

### ISSUE THREAD

**Issue by ranzbak** [badgeteam/why2025-hardware#100]
The two holes to connect the extension board left and right of the C6 need space in the spacer to hold the screws, are these spaces present in the design ? 

![image](https://github.com/user-attachments/assets/fe90a05b-f271-4a04-a076-bcdd48d17b48)

**Comment by renzenicolai** [comment]
There are nuts in the spacer for receiving a bolt attached through a housing from the back.

**Comment by ranzbak** [comment]
Perfect, that closes this issue.
