### ISSUE TITLE
Flash chip pinout

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#12]
- [ ] Use correct flash chip pinout

**Comment by JayVisschedijk** [comment]
W25Q128JVS and U8C seem to match the datasheets, what am I missing?

**Comment by renzenicolai** [comment]
If you look at the old version of the design you will find that the data pins of the flash chip haven't been connected to the right pins on the P4. I've fixed that already in the main branch so this issue can be closed.
