### ISSUE TITLE
Backlight dimming

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#14]
Current approach with PWMing the enable signal isn't working great.

Research why, maybe find other methods for dimming backlight.

**Comment by ranzbak** [comment]
- Suggestions: Make the connection to the 10uF capacitor thicker, to lower inductance.
- The PWM frequency is too high for the chip to follow? 

They suggest something above 25kHz in the datasheet, but in the picture below it's up to 25kHz PWM.

So test with 25kHz PWM?

https://www.diodes.com/assets/Datasheets/AP3032.pdf page 10
