### ISSUE TITLE
Power switch for USB-A port and addressable LEDs

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#17]
Add a power switch to turn off the USB-A port in standby mode. Disabling the booster in the PMIC does not result in 0 volt on the 5v pin of the USB connector but instead leaves VSYS on that line. It should be completely turned off.

Also a power switch would allow for setting a current limit.

**Comment by ranzbak** [comment]
We can put in a p-channel FET, it'll be a small drop in voltage.

Something like this part ? https://www.lcsc.com/product-detail/MOSFETs_HXY-MOSFET-HXY2305AI_C3033391.html


![image](https://github.com/user-attachments/assets/1fb87f34-9fd7-4f00-be49-eda0ebdcfbf9)
