### ISSUE TITLE
Connector of LCD

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#18]
Current connector is too wide, replace with smaller replacement connector and adjust footprint.

Correct connector: DF37NB-24DS-0.4V(51)

https://www.digikey.nl/en/products/detail/hirose-electric-co-ltd/DF37NB-24DS-0-4V-51/2230603

**Comment by ranzbak** [comment]
https://github.com/badgeteam/why2025-hardware/pull/32

**Comment by renzenicolai** [comment]
To-do: verify that new connector is in the correct physical location.

**Comment by ranzbak** [comment]
We need to do that with a real prototype I guess :-).
