### ISSUE TITLE
Speaker gets hot

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#23]
Needs research.

One idea is that we may even be able to get away without the amplifier.

- [ ] Test how loud the speaker is when directly connected to the DAC.
- [ ] Test if HPCOM can be used to control speaker on/off.
- [ ] Test if transistor can be used to switch low side of speaker (add diode?).

**Comment by ranzbak** [comment]
Please check out : https://github.com/badgeteam/why2025-hardware/pull/29
