### ISSUE TITLE
Unstable power rail / USB device port connection

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#25]
Needs some more testing and research, the VSYS rail seems very unstable.

**Comment by renzenicolai** [comment]
Turns out you can configure the current taken from the usb device port on the PMIC. We did that and now it's stable.

**Comment by ranzbak** [comment]
Close this one in that case?

**Comment by renzenicolai** [comment]
Nah, needs some more playing around with. For example the USB-A port can still cause the P4 do go into brownout so there is more stuff wrong here. I think it's mainly to do with the voltage on the VSYS rail still. Maybe we should look for a DC-DC for the 3.3v rail that can handle lower input voltages.

**Comment by renzenicolai** [comment]
Check that the DC-DC has a low enough minimum input voltage to be able to use the whole battery.
