### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#27]
- Check if we can find an 18650 battery holder with a footprint that fits in the keyboard matrix area
 - Maybe move the keyboard matrix wiring to an inner layer, we don't need the 3.3v power layer on the lower half of the board anyway.

**Comment by ranzbak** [comment]
The battery at the bottom, wouldn't that be more stable? 
Also we might want to tape the battery to the prototype and see where it holds best.
Also with the battery at the bottom it might even stand up by it self. (bonus)
