### ISSUE TITLE
Turn on backlight by default

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#28]
When the CH32V203 isn't active the display backlight should be on at full brightness.

**Comment by ranzbak** [comment]
Given that the pb3 will be high impedance after reset, pull the pin up using the 100k resistor to VCC?
@Renze, do you know if the pin is in high impedance after reset, or when the ch32v203cxt6 is disabled, I couldn't find in the datasheet.

**Comment by ranzbak** [comment]
Done
