### ISSUE TITLE
Add Bosch sensors

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#36]

**Comment by JayVisschedijk** [comment]
Design symbol, footprint, test board for sponsored Bosch sensors

**Comment by JayVisschedijk** [comment]
How many sensors are we talking about? And do we already know which ones specifically?

**Comment by renzenicolai** [comment]
Position sensor BHI360 and gas sensor BME690 :smile:

**Comment by JayVisschedijk** [comment]
For the BHI360 symbol and footprint:
https://www.snapeda.com/parts/BHI360/Bosch/view-part/

About the BME690 I can't find enough info on their site, did we receive inside information we can use to create a symbol and footprint?

**Comment by renzenicolai** [comment]
BHI360 needs 1.8v IO voltage. That's a bit annoying because we'd need to add a regulator and a level shifter for the I2C bus.
