### ISSUE TITLE
CH334R can operate without crystal, option ?

### ISSUE THREAD

**Issue by ranzbak** [badgeteam/why2025-hardware#60]
In the datasheet, chapter 6.2:

6.2 Crystal-free Application, Bus-powered

**Comment by renzenicolai** [comment]
I'm not sure the CH334R can be ran without crystal. However it is easy enough to test this by removing the crystal and shorting a specific signal pin to ground. I can try testing this on one of the non-working boards tomorrow.

**Comment by renzenicolai** [comment]
Tested, doesn't work with the version of the CH334R we have.

**Comment by arturo182** [comment]
The datasheet is a bit confusing on this, like it's a specially ordered version? 
![image](https://github.com/user-attachments/assets/b2cc572b-b027-4dc1-91cf-ba75beed3f48)
