### ISSUE TITLE
Add pull-up resistor to GPIO34

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#69]
For using the JTAG interface GPIO34 (E2 on the internal expansion port) can be used to select between USB jtag and the JTAG pins on the external expansion port.

Add a pull-up resistor to E2 (GPIO34) to select USB jtag by default on boards where this fuse has been burned.

 - burn JTAG_SEL_ENABLE to 1
 - pull E2 (GPIO34) low
 - reset ESP32-P4

Maybe we could add a footprint for a 10-pin JTAG header too somewhere?

**Comment by renzenicolai** [comment]
Extra ideas:
 - Add testpoint to P4 reset pin next to the RX and TX pins
 - Add solder jumper for shorting E2 to ground

**Comment by ranzbak** [comment]
Pullup resistor 51K added to GPIO34.

Leaving the ticket open for a bit to see if there is space for a 10 pin JTAG header.

**Comment by renzenicolai** [comment]
Continued in #82
