### ISSUE TITLE
Add P4 reset to the expansion header

### ISSUE THREAD

**Issue by Orange-Murker** [badgeteam/why2025-hardware#74]

**Comment by ranzbak** [comment]
What pin do we disconnect from the expansion header to make space?

**Comment by renzenicolai** [comment]
none, of we can add a 10 pin jtag header that would be amazing (like mentioned in #69)

if not then we could just add either a small extra header footprint or extend the side exp. header by two pins

**Comment by renzenicolai** [comment]
Continued in #82

**Comment by renzenicolai** [comment]
Might still be useful to add an extra 1x02 to the external expansion port, containing JTAG detect and P4 reset

**Comment by renzenicolai** [comment]
Solved by assigning GPIO34 as SAO IO 2 to allow selecting JTAG mode and exposing the P4 reset on one of the PMOD power pins.
