### ISSUE TITLE
Add PMID SW diode for better stability and efficiency of the PMIC

### ISSUE THREAD

**Issue by ranzbak** [badgeteam/why2025-hardware#77]
SW to PMID diode Help to improve the efficiency. Recommend for applications with greater than 2.4A boost mode ouput.

From this document : https://e2e.ti.com/cfs-file/__key/communityserver-discussions-components-files/196/BQ25895_5F00_SchematicChecklist-V1p1.pdf

Since we see VBatt / VSYS interactions, and have problems at high current, we might want to add this diode.

![image](https://github.com/user-attachments/assets/186fbb8d-250b-41b6-8975-d82ae800e58a)

**Comment by ranzbak** [comment]
In commit d410a64c0f7fcd8e44ddb87f60cdcf2cb8bcdb74 the Diode has been added, this should at least make the OTG power more reliable.

**Comment by renzenicolai** [comment]
Seems fixed.
