### ISSUE TITLE
CH334R does not have enough capacitance on 3v3 

### ISSUE THREAD

**Issue by ranzbak** [badgeteam/why2025-hardware#79]
The current schematic puts 100n + 1u on pin 13 of U4.

According to the datasheet page 27 this should be 100n + 10u

In the description below the schematic it's stated that in case of stability, this can be increased to 22uF.

![image](https://github.com/user-attachments/assets/6f9e1ae8-2e2d-4f56-bce0-357c762d4f62)

**Comment by ranzbak** [comment]
Change the 1u to 10u, add another unpopulated 10u footprint next to the crystal in case it's needed.

**Comment by renzenicolai** [comment]
Changed to 10u, added another footprint for a 10u, also added an extra 1u on VSYS

**Comment by renzenicolai** [comment]
Extra capacitors have been added, so this ticket can be closed.
