### ISSUE TITLE
Bosch environmental sensor: switch to BME688

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#86]
Switch Bosch sensor to https://jlcpcb.com/partdetail/BoschSensortec-BME688/C3664478

**Comment by ranzbak** [comment]
This IC does not have a Gyroscope/accelerometer, is this feature going to be dropped?

**Comment by geekyjoyce72** [comment]
That would be the separate BHI360 chip

**Comment by ranzbak** [comment]
Thanks, replace the BME680 with the BME688 on the design, pushed result, please close after verification.

**Comment by renzenicolai** [comment]
Note: design has two Bosch sensors:

A BHI360 for position sensing

and the BME688 for environmental sensing. The BME680 is pin-compatible with the BME688.
