### ISSUE TITLE
Swap E2 and SAO IO2

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#88]
E2 (GPIO34) en SAO IO2 (GPIO0) omwisselen op de P4 zodat we krijgen: E2=GPIO0, SAO IO2=GPIO34

**Comment by ranzbak** [comment]
Fixed in commit 5833a04e83a3e18b5ff4a887d21beb78078f4aec, Pin 13 of the connector can now double as P4 reset.

**Comment by ranzbak** [comment]
Close when verified please.
