### ISSUE TITLE
I2C bus lockup when enabling C6

### ISSUE THREAD

**Issue by renzenicolai** [badgeteam/why2025-hardware#89]
Sometimes the coprocessor stops responding for a bit when enabling the C6, exact origin of the problem is unknown, logic analyzer testing needed.

**Comment by ranzbak** [comment]
Coprocessor = ch32 I presume?

Is this during the startup sequence (In other words how is the problem reproduced)?

**Comment by ranzbak** [comment]
Question : 
bsp_platform_init:26
The maximum_speed is net set, could this be related?

**Comment by renzenicolai** [comment]
Workaround: bus recovers quickly after C6 causes weird behaviour. Solved by allowing bus errors to occur and properly recovering from them.
